- src/winetricks
Without this fix, it is impossible to install msxml6 on 64-bit Wine prefix with winetricks.
> The ability to install msxml6 (x86 and x64 version) on 64-bit Wine prefix

- src/winetricks
Commit https://github.com/Winetricks/winetricks/commit/84906b01114330595c37abbeba89c0b450df9a98 introduced a hardcoded `wine64` path, which would break the installation if a non-default wine version is used.
Unfortunately the `msxml6.dll` recipe needs a 64-bit `msiexec` to work properly. We do that by spawning 32-bit `start`, which then starts 64-bit `msiexec` (using the `C:\Windows\sysnative` path). This only works as long as the `$WINE` environment variable really specifies the 32-bit wine version, but I assume there are a lot more recipes depending on that... and its better than doing path manipulations! ;)
> Avoid hardcoded wine64 path in msxml6 recipe.

- src/winetricks
Add d3drm.dll which is required for some ancient games using directx retained mode (for example Lego Rock Raiders).
> winetricks: add d3drm verb

- src/winetricks
The first patch adds an easy way to install a native dbghelp override. The second patch adds recipes to install ollydbg (especially useful for wine developers). Please note that there are a couple of good reasons why I am adding multiple versions:
* ollydbg201 is affected by wine bug https://bugs.winehq.org/show_bug.cgi?id=36012 (if wine is compiled with debug symbols). It can be worked around with native dbghelp, but depending on the situation this might be not a suitable solution. In such a case its nice to have older versions as fallback.
* Between ollydbg1* and ollydbg2* there was a full rewrite. Various old features were removed and new features were added. Moreover the plugin interface changed. Depending on the situation its still necessary to use an old version.
> Add dbghelp and ollydbg* verbs.

- debian/control
This patch mimes the dependency behavior of the Ubuntu winetricks package and marks Wine as an optional dependency which gets installed by default. The change makes it possible to use winetricks with 3rd party of self compiled wine versions without forcing the user to install the distro provided wine package.
> debian: Make wine an optional dependency

- src/winetricks
Some games do not ship a binkw32.dll (somehow required for video rendering?), having a winetricks recipe for that makes it easier to test such bugs. One example is: https://bugs.wine-staging.com/show_bug.cgi?id=155
Some comments on the patch:
* The changes to `w_download_to` are required since the webserver is not happy with winetricks passing the accept-encoding header, and wget returns a gzip compressed result. The replacement `*gzip*` -> `*:*gzip*` was done to make sure it doesn't accidentially match the filename instead of the file type. **Needs testing on MacOS/BSD!**
* Metadata information is based on the file metadata.
* I know that `down-dll.com` is probably not really the best mirror, but the checksum matches the expected one, and it doesn't require any cookies. If it breaks we …
> winetricks: add binkw32 verb

- src/winetricks
The current winetricks version of Kindle for PC won't login to Amazon -- Amazon has this thing about trying to make you run the latest version of their software -- and I am not sure it will still auto-update either.
Ideally the user should always install a reasonably recent version of Kindle for PC, or Amazon may refuse to let it work...
> Update the version of Kindle for PC.

- src/winetricks
Made _W_path a local variable in function w_get_sha1sum to prevent it from overwriting the value set in the main script.
> Fixed "mv: cannot stat" error on failed SHA1 chksum

- src/winetricks
```
$ winetricks dotnet45
Executing w_do_call dotnet45
/usr/bin/winetricks: 1968: test: dotnet20: unexpected operator
error: dotnet45 conflicts with dotnet20sp2, which is already installed.
```
It doesn't appear to have any adverse affects (it is reporting the conflict correctly), but the test fails. I have modified the check to use the exit code of grep -q (indicating the presence of matches), rather than testing for matches using test.
> Fix a broken test in non-bash shells

- src/winetricks
Please double-check this but it seems the $1 argument to w_get_sha1sum needs quotes. I've seen failures on multiple verbs with spaces in the executable names until I add quotes to the argument as in this patch.
Example, when loading dotnet45:
...
Executing load_dotnet30sp1
./winetricks: 504: local: 2003: bad variable name
The file being executed is:
~/.cache/winetricks/dotnet30sp1/XPSEP XP and Server 2003 32 bit.msi
> winetricks crashes on installers with space in name

- src/winetricks
This patch makes "xmllite" installable on ja_JP locale.
> xmllite: Add Japanese support

- src/winetricks
The SDK 7.1 provides the 10.0 compiler toolchain, whereas the SDK 7.0
only provides the 9.0 compiler toolchain.
> Add MS Windows SDK 7.1 verb

- src/winetricks
winetricks needs to use it's own download dir settings when downloading with aria2. This patch will make winetricks override any custom '~/.aria2/aria2.conf dir=' setting.
If this is an accepted fix for the problem, please consider merging.
Cheers!
> aria2 - override conf download dir setting

- src/winetricks
Some software (e.g., Exact Audio Copy) rely on this font in order to display Japanese text
> Add "MS UI Gothic" alias

- src/winetricks
Add versions to w_workaround_wine_bug (#25715 and #25716).
Wine bug [#25715](https://bugs.winehq.org/show_bug.cgi?id=25715) is fixed in Wine 1.7.28, and [#25716](https://bugs.winehq.org/show_bug.cgi?id=25716) is fixed in 1.7.29.
> dxdiag: Add versions to w_workaround_wine_bug

- tests/winetricks-test
`type` will also report for builtin shell commands like `time` which we don't want.
On ArchLinux for bash 4.3 `type time` returns 'time is a shell keyword' and thus it will pass even if I don't have `time` installed.
> Use `which` instead of `type`

- src/winetricks
dotnet_verifier was updated so need to update it's hash
```
July 31, 2015        - Add the ability to verify the .NET Framework 4.6. Updated tool to
allow it to differentiate between Windows 8.1 and Windows 10.
```
> Update hash for updated dotnet_verifier

- src/winetricks
DirectMusic test doesn't work without native DirectMusic DLLs (Wine bug [#9027](https://bugs.winehq.org/show_bug.cgi?id=9027)) and gm.dls.
> dxdiag: Use native DirectMusic DLLs and gm.dls

- src/winetricks
Install "Managed DirectX" which is required by some .NET applications (e.g. Bve trainsim).
This can be installed by "winetricks directx9", but other DLLs are also installed/overridden.
Note: Bve trainsim also requires "dotnet35" and "d3dx9_36".
> Add "Managed DirectX" verb

- src/winetricks
"February 2010" redistributable package doesn't contain d3dx10_43.dll.
Use "June 2010" version instead.
> d3dx10: Install d3dx10_43.dll

- src/winetricks
Install also 64bit DLL(s) if wineprefix is 64bit.
Verbs (already tested):
d3dx9, d3dx9_26, d3dx9_28, d3dx9_31, d3dx9_35, d3dx9_36, d3dx9_39, d3dx9_42, d3dx9_43, d3dx10, d3dx11_42, d3dx11_43, d3dcompiler_43, xact, xact_jun2010, xinput
> d3dx9*, d3dx10, d3dx11*, d3dcompiler_43, xact*, xinput: Add x64 support

- src/winetricks
Install also 64bit DLLs if wineprefix is 64bit.
> vcrun2012, vcrun2013: Add x64 support, closes issue #559

- src/winetricks
cabextract fails if wineprefix is 64bit.
This patch fixes this.
> vcrun2015: Avoid permission error

- src/winetricks
The original "samyak|oriya" regexp matched against "Noto Sans Oriya", creating a false alarm.
> fontfix: match both "samyak" and "oriya" in font names

- src/winetricks
The new version has features that might be undesirable, especially to anyone who absolutely must use an old E-Ink ereader. ;)
I chose to use adobe_diged4 for the new version, since the old version is known to be reliable, does not require winbind/samba which may or may not be installed, and also because I subjectively feel it should be the default. :wink:
Also provide a warning when installing ADE 4.5 if winbind is not detected, since the application fails to actually run without it.
These changes are in reference to comments made in #561
> Offer both old and new versions of Adobe Digital Editions.

- src/winetricks
Set sound driver to PulseAudio.
Note: PulseAudio support is available since Wine 1.7.55.
> Add "sound=pulse" verb

- src/winetricks
Add winetricks settings to toggle hiding wine exports feature available in wine staging. See https://github.com/wine-compholio/wine-staging/blob/master/patches/ntdll-Hide_Wine_Exports/0001-ntdll-Add-support-for-hiding-wine-version-informatio.patch
> Add hidewineexports setting

- src/winetricks
I am not sure about the need of this addiction on ahk script, but at this time it seams to be unused.
> Correct carriage return conversion on w_ahk_do()

- src/winetricks
installing steam from winetricks fails because of a sha1sum mismatch (probably due to a new version of the steam installer)
just updated the sha1sum of the new executable so it can run
> updated sha1sum of steamsetup.exe

- src/winetricks
Hi
Debian provides /usr/bin/wineserver since wine 1.8-2. So the existing workarounds for finding the wineserver are only needed for older Debian versions.
However for wine-development the wineserver will be /usr/bin/wineserver-development. I added that to the list and the binary detection code.
Thanks a lot
jre
> Adapt to new Debian /usr/bin/wineserver[-development].

- src/winetricks
The old redirect is hard to swallow
> A real albeit untidy help page

- src/winetricks
With this patch it is possible to use "winetricks --self-update|--selfupdate" to automatically update the script with the last online version. Also, it is possible to rollback an update by running "winetricks --update-rollback".
This patch is a proposal and can be improved. Let me know if it is useful and if you want some adjustments.
> Self-update functionality for winetricks.

- src/winetricks
Workaround no longer needed (https://bugs.winehq.org/show_bug.cgi?id=34897, comment 16), bug number changed.
> Update ev3 verb

- src/winetricks
Fixes #650, tested with Python3.5, 32/64 bits, wine 1.9.8/1.9.11.
> Override more vcrun2015 dlls for 32 bits prefix

- src/winetricks
- tests/winetricks-test
As per comment on 1e0cefd4b8ace60d6f7c7fc5309192f67eba5b57, this commit removes all the double-quotes around $() expressions, except in those cases where double-quotes were already present back when backticks (``) were used.
> winetricks: get rid of unneccessary double-quotes around $()

- src/winetricks
this patch removes copy-paste code and masks direct run aria2c and torify (need against shell code requirement tools).
> use detected torify and torify options for aria2c

- debian/control
- src/winetricks
Document use of ar, see #652. I think it's better to explicitly mention it, although there's now a fallback to 7zip. Adjust the Debian packaging accordingly.
While at it, change Ubuntu installation instructions from versioned "wine1.7" to unversioned "wine". This should work on every Ubuntu releasse, and give the default Wine version for that release. Of course there's a small drawback of eventually not getting the newest Wine, but changing the version manually here is likely to be outdated.
> Documentation (binutils, ar, unversioned wine)

- src/winetricks
`open FILE, $ARGV[0] || w_die "can't open ".$ARGV[0];` breaks colorer ( http://colorer.sourceforge.net/ ).
Please merge.
> Unpack "can't" to fix colorer highlighting

- Makefile
- src/winetricks
These are low-hanging fruits to use native utilities on FreeBSD.
> FreeBSD work 1/?

- src/winetricks
CSDVersion is an empty string on Windows 8 and up, from https://source.winehq.org/git/wine.git/commitdiff/f94784ddbac9880789171d9f0126499485051249
> winetricks:CSDVersion is empty on Windows 8 and up

- src/winetricks
All the URLs updated in this commit are broken links, but it's still possible to upgrade them to use HTTPS without altering their behaviour and returned results, while improving privacy/security. Some old-style URLs were updated to follow the initial redirect to newer style ones.
This completes the work started in https://github.com/Winetricks/winetricks/commit/a528fd1ecf6132535704e9baf1642b7e0b589a4d.
> use HTTPS in MS URLs that no longer work

- src/winetricks
Just a few minor typos in messages/comments. Just tell me if I should split them up, or whatever.
> src/winetricks: Fix typos in comments and messages.

- src/winetricks
The Internet Archive seems to be having some issues, but setting an early date seems to allow most files to download.
Tested with `msxml3` in a fresh prefix.
Closes #773.
> Fix downloading some links from Internet Archive

- src/winetricks
Release 8 replaced with release 9. SHA256 checksum fixed.
Original Debian repository was used to download the .deb file.
> Fixed URL and checksum for fonts-opensymbol package

- src/winetricks
Noticed these when working on an ie8x64 verb.
> Small tweaks to IE8 verb

- Makefile
- src/winetricks.appdata.xml
AppStream is a cross-distro XML format to provide metadata for software components and to assign unique identifiers to software. The metadata can for example be used by software centers like GNOME Software or KDE Discover to display a user-friendly application-centric way on the package archive.
This PR adds an AppStream AppData file.
> Add AppStream appdata file

- src/winetricks
"sort -V" is not supported on OS X and older coreutils. "sort -n -t. -k1 -k3" supports sorting of "abc x.x.x".
> replace "sort -V" with "sort -n -t. -k1 -k3"

- src/winetricks
For https://bugs.winehq.org/show_bug.cgi?id=43841
> speechsdk: wine-2.18 ships a stub sapi.dll, work around it

- src/winetricks
I spotted these while digging through the script in Sublime because they confuse the syntax highlighter.
> Add a couple of missing double semicolons

- src/winetricks
If ~/.cache/winetricks did not exist, this failed before:
```
$ ./winetricks 
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
Using winetricks 20171018-next - sha256sum: e586dbf0ebdd7969b558e1e03372bfd7e735a98a33e95bdad32d831e6b2cc2db with wine-2.18 (Debian 2.18-1+wip1) and WINEARCH=win64
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
./winetricks: …
```
> tracking stats: create cache directory if needed

- src/winetricks
I noticed this font was omitted (probably by accident) from the `eufonts` package.
> Add missing Arial Bold EU Font

- src/winetricks
This is an attempt to resolve https://github.com/Winetricks/winetricks/issues/861 I don't know any highly portable solution for generating random numbers in shell scripts, so I leveraged the existing `w_get_sha256sum` verb in order to get a unique string to append to the name of each file that gets placed in `$W_TMP_EARLY`.
I didn't want to append the font name to the file name because it might contain weird characters, but I'm OK to do that instead of the truncated sha256 if you think it's safe enough.
> Backup font reg files properly

- src/winetricks
This was breaking on CI for us, looks like the URL has been updated
> Update netfx_setupverifier_new.zip URL

- .travis.yml
[pip got removed in the latest OSX Travis image](https://github.com/Winetricks/winetricks/pull/888#issuecomment-350048432), so we have to install it manually for now.
> misc: fix OSX builds on Travis

- src/winetricks
This is an attempt to partially address #865 and clean up some inconsistencies in the font-related verbs.
- Add verb `w_try_cp_font_files`, which makes sure that we don't get the same font file but with different casing under `C:\windows\Fonts`. It also forces lower case for font names to help alleviate duplication issues.
- Cache PowerPointViewer.exe in "$W_CACHE/PowerPointViewer" for consistency.
- Remove "# FIXME: why is this commented out? Should be removed or enabled." comment. This was referring to the Andalé Mono font, which is [no longer distributed with Windows](https://en.wikipedia.org/wiki/Andal%C3%A9_Mono#Distribution). If you wish, I can create a separate verb for it since it's available [here](https://mirrors.kernel.org/gentoo/distfiles/andale32.exe), but I think we don't …
> Fix font duplication

- src/winetricks
This fixes #880.
Bonus: It seems to make Font Xplorer ([available as a verb](https://github.com/Winetricks/winetricks/blob/a864b065339551995b9ecdfd9ea3a4be85c5da93/files/verbs/apps.txt#L15)) happy when inspecting the Cambria font. Before this fix, it was claiming that Cambria is not installed. There are some other fonts that exhibit this behaviour, but I haven't yet investigated why (and I hope to not have to :P).
> w_register_font: Register TTC fonts as TrueType

- src/winetricks
This fixes #885.
With this fix, eufonts is no longer skipped when installing allfonts (a regression introduced by #888).
> winetricks_is_installed: return false if the verb hasn't been run before

- src/winetricks
This is a potential fix for #896.
The latest wine-devel (wine-3.0-rc2) as well as previous versions seem to forget to lock the registry when inserting entries automagically into `HKCU\Software\Wine\Fonts\Cache`, after a font file has been copied in `.wine/drive_c/windows/Fonts/`. From my tests, this change seems to address this issue, although it does slow down font installation a bit.
Note: This issue was happening even before `w_try_cp_font_files` got added.
> w_try_cp_font_files: Prevent registry writes race

- src/winetricks
As described in #896, the liberation fonts should be registered differently in the registry.
I'll open a new bug and PR if we'll end up not needing to register fonts manually into the registry.
> load_liberation: Write the correct font names to the registry

- src/winetricks
This fixes #881, and it's probably relevant only for apps which list fonts manually from the registry. Wine seems to return the fonts that are under `HKCU\Software\Wine\Fonts\Cache` when calling `EnumFontFamiliesEx` and it creates both `Cambria` and `Cambria Math` entries automatically, which is great because it seems to support TTC files quite well:
> load_cambria: Register Cambria Math

- src/winetricks
This seems to be fixed by #900. Also, Font Xplorer no longer lists it as "not installed".
> load_tahoma: Remove outdated FIXME

- src/winetricks
I think it's best to revert this fix, because [according to Huw](https://www.winehq.org/pipermail/wine-devel/2017-December/120684.html):
> Fonts without a path correspond to c:\windows\fonts.  These files
> should be installed into that directory.
Also, it doesn't seem to work well on my Ubuntu installation. See #902.
> w_register_font: Revert 2c2b44e because it's not needed

- files/verbs/all.txt
- files/verbs/settings.txt
- src/winetricks
In a server environment, we usually need a process to restart automatically if it crashes. Having winedbg start on each process crash will flood the server with hanged processes.
This new verb allows users to disable this behaviour and I use it in combination with `nocrashdialog`, because I am running a process in headless mode under Docker (using Xvfb).
Relevant documentation: https://wiki.winehq.org/Wine_Developer%27s_Guide/Debugging_Wine#Windows_Debugging_configuration
> autostart_winedbg: new verb

- .travis.yml
Ubuntu Zesty (17.04) reached End of Life on January 13, 2018.
We need to switch to Artful (17.10).
See also: https://wiki.ubuntu.com/Releases
Note: Xenial (16.04 LTS, End of Life = April 2021) is available on Travis CI (experimental), but shellcheck is too old (0.3.7).
> travis.yml: switch to Ubuntu Artful (17.10)

- src/winetricks
Wine now has l3codeca.acm, wmplayer.exe, and a version resource for wmvcore,
so we need to remove and override these as well.
wmp9 also tries and fails to install msdmo, which I've left alone for now.
> wmp9: update overrides

- src/winetricks
* allfonts: don't call verbs for font replacements (fake*) or "pptfonts" metapackage
* This prevents `allfonts` from adding font replacements
* `pptfonts` can be skipped because it only calls other verbs for installing fonts
* cjkfonts: call fakejapanese_vlgothic
* Now it adds font replacements for Meiryo
* fakejapanese_vlgothic, meiryo: conflict each other
* Wine uses Meiryo when both are installed
winetricks.log after installing patched `allfonts`:
```baekmuk
calibri
cambria
candara
consolas
constantia
corbel
corefonts
droid
eufonts
ipamona
liberation
lucida
meiryo
opensymbol
tahoma
takao
uff
unifont
vlgothic
wenquanyi
allfonts
```
winetricks.log after installing patched `cjkfonts`:
```wenquanyi
fakechinese
takao
fakejapanese
vlgothic
fakejapanese_vlgothic
baekmuk
fakekorean
unifont …
```
> Font replacements related fixes

- src/winetricks
Builtin wine's `iccvid.dll` has very limited compatibility with original Cinepak Codec.
I found a lot of people complaining that videos are not working in their best games under wine.
Proposal is to add support for native cinepak codec into winetricks to simplify configuration for these games.
Examples: https://bugs.winehq.org/buglist.cgi?quicksearch=cinepak&list_id=575861
I personally was able to run properly Earth 2150: https://www.artembutusov.com/setup-earth-2150-game-on-os-x-thru-wine/
> Support for Cinepak Codec by Radius

- src/winetricks
This allows users to select individual DirectMusic DLL(s).
The new verbs are: `dmband`, `dmcompos`, `dmime`, `dmloader`,
`dmscript`, `dmstyle`, `dmusic`, and `dswave`.
Applications that use [GuruGuruSMF library](http://gurugurusmf.migmig.net/) need only `gmdls`, `dmsynth`, and `dmusic`. [This attachment](https://github.com/Winetricks/winetricks/files/1044945/playsmf-gurugurusmf.zip) is a small sample (command-line MIDI player). [WOLF RPG Editor](http://www.vector.co.jp/soft/winnt/game/se475870.html) also uses this library.
[Easy Music Player](http://pf-j.sakura.ne.jp/download/emplayer.htm) needs additional native DLLs to use Microsoft Synthesizer: `dmime`, `dmloader`, and `dmband`. `dmstyle` is not necessary, but recommended because `fixme:dmstyle:IDirectMusicTrack8Impl_PlayEx ... stub` …
> directmusic: Split into multiple verbs

- src/winetricks
* cod1: fix typos (w_try_cd -> cd)
* w_download_to: exit from loop when download succeeded
* Without this, `winetricks_dl_warning()` is called even if a file is successfully downloaded. This is meaningless.
> Small fixes

- src/winetricks
* `adobeair` (`29.0.0.112`): `5186b54682644a30f2be61c9b510de9a9a76e301bc1b42f0f1bc50bd809a3625`
* `shockwave` (`12.3.2.202`): `4d7b408cf5b65a522b071d7d9ddbc5f6964911a7d55c418e31f393e6055cf796`
> adobeair, shockwave: update sha256sum

- src/winetricks
Fix #947.
In addition, the last commit changes `dxdiag` to use minimal override set for DirectMusic (Related: #806).
> dxdiag-related changes

- src/winetricks
As discussed on [issue 937](https://github.com/Winetricks/winetricks/issues/937) this is a MR for office2013 support.
> Feature office2013pro

- files/verbs/settings.txt
- src/winetricks
Since Wine 3.3, CSMT is enabled by default (see https://www.winehq.org/announce/3.3).
However, the setting options CSMT is by default disabled according to
the Winetricks settings menu. This commit updates the titles for these
options to the correct ones. It also swaps the order of the CSMT options,
since in most cases the default option is the top setting.
> verbs: CSMT enabled by default

- src/winetricks
These are known to be broken in Wine, see Wine Bug 41618 comments 5 and
6. This also adds overrides for the 32-bit DLLs, since Wine now prefers
built-in.
> xact: Don't install 64-bit xact libraries

- .travis.yml
- misc/travis-install-bashate-deb.sh
- misc/travis-install-bashate-pip.sh
The new script `travis-install-bashate.sh` installs bashate
by unpacking .deb files built for Ubuntu Bionic (18.04 LTS).
This also reduces job time.
Ubuntu Bionic will be supported until April 2023.
Also, ShellCheck is already available on Ubuntu image and
we don't need to install it.
> travis.yml: install bashate with .deb files for Ubuntu 18.04 LTS

- src/winetricks
* `pptfonts` (`calibri`, `cambria`, `candara`, `consolas`, `constantia`, `corbel`, and `meiryo`): Use alternative URL because PowerPoint Viewer is no longer available from Microsoft
* `gmdls`: Use DirectX April 2006 instead of DirectX 8 because it seems that DirectX 8 redist is available only in archive.org
* The file (`gm.dls`) is the same as DirectX 8 (sha256:`3229b09b9d7d9f3f4793b0d9b34fe6abc75cfa4a2503c0c90f43ff651ba7f2c0`)
> URL updates for pptfonts and gmdls

- src/winetricks
RE: https://github.com/Winetricks/winetricks/issues/999
Went with the standard **winetricks** way of installing the dll's directly to the **Wineprefix**.
TBH the whole Upstream symlinking script gets quite messy... The **dll** files are a few Mb's...
The data files for **GTA V** are in the 10's Gb - enough said really... :-)
> dxvk: new verb

- src/winetricks
Add registry settings, and **winevulkan.json** file, required by
**winevulkan** to use the installed Vulkan version instead of
the builtin **vulkan-1.dll** implementation.
Tested with a clean **64-bit WINEPREFIX**, using:
wine vulkaninfo.exe
to confirm correct installation and operation.
> Fix vulkansdk verb

- src/winetricks
E.g. Gentoo multi-slotted Wine variants could be of the form:
**wine-staging-9999**
**wine64-staging-9999**
> Fix handling the case where wine binaries have a suffix

- debian/control
- src/winetricks
This aims to migrate from "`sudo` + `mount`" to FUSE-based tools (`fuseiso` or `archivemount`) or `hdiutil` in a phased manner.
To use them, insert `W_USE_USERMOUNT=1` before first `w_mount()` call.
This is reset automatically at the end of verbs.
The following verb (`debuggingtools.verb`) is already tested (passed) on Ubuntu and macOS in TravisCI.
```sh
w_metadata debuggingtools apps \
title="Debugging tools" \
publisher="Microsoft" \
year="2010" \
media="download" \
file1="WDK.iso" \
installed_exe1="$W_PROGRAMS_X86_WIN/Debugging Tools for Windows (x86)/windbg.exe"
load_debuggingtools()
{
w_download "https://download.microsoft.com/download/4/A/2/4A25C7D5-EFBE-4182-B6A9-AE6850409A78/GRMWDK_EN_7600_1.ISO" 5edc723b50ea28a070cad361dd0927df402b7a861a036bbcf11d27ebba77657d "WDK.iso" …
```
> Add functionalities that mount/unmount ISO images with FUSE-based tools or hdiutil

- src/winetricks
This PR fixes the following:
* `w_override_dlls native d3d11.dll dxgi.dll` doesn't work because it contains `.dll`
* `_W_dxvk_dir` is not unset
> DXVK fixes

- src/winetricks
Fixes #1029
Related verbs:
* Verbs that use `helper_win2ksp4` (e.g. `winhttp`): `https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE`
* Verbs that use `helper_winxpsp3` (e.g. `msctf`): `https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/winxp/Service_Packs/WindowsXP-KB936929-SP3-x86-ENU.exe`
* `cabinet`: `http://ftp.gunadarma.ac.id/pub/driver/itegno/USB%20Software/MDAC/MDAC_TYP.EXE`
* `cmd`: `https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Security_Bulletins/Q811493_W2K_SP4_X86_EN.exe`
* `dotnet30`: `http://descargas.udenar.edu.co/Framework.net/dotnetfx3.exe`
* `mdac27`: `http://ftp.gunadarma.ac.id/pub/driver/itegno/USB%20Software/MDAC/MDAC_TYP.EXE`
* …
> Replace FTP download URLs with HTTP(S) URLs

- src/winetricks
This verb just removes Wineprefix symlinks to the Wine user's
$HOME directory. Complementary to the sandbox verb.
> Add verb isolate_home

- src/winetricks
Add warning about wine version (>=3.10) requirement.
> Update dxvk verb to version 0.60 (released 22 June 2018)

- src/winetricks
The DXVK Vulkan header version was raised to 1.1.80. However Philip says he isn't using any newer extensions - so that is not a strict requirement.
> dxvk63: new verb

- src/winetricks
Put simply the core fonts project have had the IELPKTH.CAB file laying around on their sourceforge account for ages, most Linux users when needing Tahoma probably find it (or a similar copy of IELPKTH.CAB) there first.
I have no rationale for wanting version 2.60 over 2.26 other than to say that if we were not interested in newer versioned fonts, then why does verb 'eufonts' exist when that's all that does?
Looking through FontForge the only thing I can see different between these versions is 10 more symbols... however both of them already have the euro symbol (so if that is the reason for the 'eufonts' verb to exist is for adding the euro symbol, that reason isn't applicable here).
Also it's worth noting that although the file currently being downloaded is called "tahoma32.exe" which …
> Swap Tahoma version v2.26 for v2.60

- src/winetricks
Fixes #1037
* `hhw`: HTML Help Workshop
* `itircl`: Native `itircl.dll`
* `itss`: Native `itss.dll`
@techtonik Could you test `https://raw.githubusercontent.com/kakurasan/winetricks/66c4090daee96017b89efb39ad1ff8d3b9b57632/src/winetricks`? Does the verb `hhw` work as you expect? I tested this and it seems it works for me.
Travis job logs:
* [395462068 (Linux)](https://travis-ci.org/kakurasan/winetricks/jobs/395462068)
* [395462069 (macOS)](https://travis-ci.org/kakurasan/winetricks/jobs/395462069)
> Add HTML Help Workshop related verbs

- src/winetricks
This pull request allows to graphically manage wineprefixes and graphically install/run custom applications which should be very helpful for new users who don't like to use the terminal.
This is realized by:
* Adding "Create new wineprefix" menu item in prefix-menu which shows a new dialog for naming the wineprefix and select its architecture (32|64 bit).
* Adding "run explorer" menu item to main-menu so that you can install/run any application graphically by double-click within the selected wineprefix.
* Adding the new verb "arch=32" which creates a new 32bit wineprefix on 64bit systems.
Bugfixes:
* Wineprefixes from "~/.local/share/wineprefixes" are missing in prefix-menu when using kdialog.
* "Show/Hide broken apps" and "Enable/diable silent install" is missing in prefix-menu when …
> Improve graphical wineprefix management and bugfixes

- src/winetricks
Might help to workaround [Bug 45847](https://bugs.winehq.org/show_bug.cgi?id=45847). According to Focht, it needs at least wininet.dll from Windows 7.
I had to add an extra override for iertutil.dll because testing QQIntl revealed that this version of wininet.dll requires it.
It would be nice if someone could test QQIntl completely. I couldn't go further than the login screen, because registration requires a phone number.
I also tried ie7 and ie8, which also use native wininet, but those are currently blocked by #911.
> wininet: update to newer version and add 64bit compatibility

- README.md
Responding to user feedback... See: [Installation using wine gets stuck at .NET Framework 4.6.2](https://forum.winehq.org/viewtopic.php?f=8&t=31452).
Linux user's don't like to copy-paste random shell scripts from the Internet! An Ubuntu user will not think to remove a previously version of winetricks - so the new / manually installed and up-to-date winetricks version will be ignored.
Updates to README:
* Breakdown the winetricks update script in excruciating detail. With helpful links to the TLDP website.
* Split off an alternative update script, to show how to set it up, without using sudo. Keeps the non-sudo users happy.
* Don't use /usr/local/bin as an installation location. Even if this is in the user's PATH, it will get lower priority than /usr/bin. So a previously installed …
> README: improve Installation and Updating guides

- src/winetricks.bash-completion
This dynamic fetch/refresh is unncessary, as global Country Codes do not
change very often.
> bash-completion: drop Internet COUNTRY_CODE fetch

- src/winetricks.appdata.xml
The license of the Winetricks project is LGPL-2.1+, not GPL-2.1.
> Fix project_license in appdata.xml.

- src/winetricks
Use $WINETRICKS_GUI prevents direct requires to zenity/kdialog binaries (it is need for correct rpm packing)
> use $WINETRICKS_GUI instead of direct zenity/kdialog call

- src/winetricks
* Steam client does not support Windows XP, as of January 2019.
> steam verb: drop Windows XP workaround, for 39403

- src/winetricks
This splits the existing verb galliumnine02 into a helper and the verb using it, then adds a verb for the new v0.3, which is also using the helper (like dxvk).
Additionally, there's also a version independent verb added, which uses the github api to fetch the latest release. We get a json formatted response, which I currently 'parse' using `grep` and `cut`.
Thanks!
> Gallium Nine bits

- src/winetricks
Minor version bump, from 12.0.30501.0 to 12.0.40660.0. Apparently fixes "some floating-point math library functions", details at the link in commit.
Link to latest version originally at https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads
> Update vcrun2013 to 12.0.40660.0

- src/winetricks
**dxvk** release **1.1** had multiple issues (referenced on Discord) with Nvidia (??) graphics cards. 
As result **dxvk** release **1.1** has been reverted by Upstream.
> dxvk developer has reverted release dxvk release 1.1

- src/winetricks
Sourceforge does not resolve the provided link anymore. Instead, A web
page is downloaded that does not match the sha256sum.
The newly provided link makes installation work again.
Closes #1142
> Update 7zip Download Link

- src/winetricks
Update Visual C++ 2017 Redistributables to download a latest version; from 14.11.25325.0 to 14.16.27027.1 as of writing. Closes #1190
> Update vcrun2017 to 14.16.27027.1

- src/winetricks
I regularly cross-test using native DLLs, so verbs for qcap and directshow are handy. I expect they may end up being handy for other users as well.
The third patch is not limited to DirectShow, but was motivated by it.
> Several improvements for DirectShow

- src/winetricks
- tests/shell-checks
For #1207 et al
@bobwya I was thinking something like this to handle the aria2c issue. I'm not set on it, obviously my sed/tr stuff could be improved, but I think this approach is simpler than trying to have one regex to rule them all. It also avoids harcoding downloader names, so should be future-safe (and good for when other downloaders break it ;)).
This also lets us it for other verbs, i.e., dxvk/etc.
What do you think? @bobwya @dhewg
> Use a helper to get github releases from github API

- src/winetricks
The old version of AHK doesn't seems to install it correctly.
I've tested it in Docker, it seems to work fine. I can't test it on my local Ubuntu, as I've proxy popup instead.
The previous code was stuck at `WinWaitActive, Installation successfully completed`, it seems AHK didn't recognise this text when the installation finished.
I've tested and installer exists it-self after installation is completed, so there is no need to click the _Finish_ button. It exists automatically and it re-runs Terminal. So the code just waits 10 seconds for installer to complete. There is no point of closing terminal at the end, I've tried some code (which can be seen in the previous commits), but it was not perfect. So the current version is the simplest.
Attempt of closing terminal process always ended up …
> Fixes MT4 platform installation

- src/winetricks
This library is used by Office 2016/2019's Click2Run updater.
> msdelta: new verb (differential compression lib)

- src/winetricks
Left by 9dc7daac7dfe51f59e3886e39d3b61cd1f933720.
> wsh56js: Fix a typo.

- src/winetricks
I went and checked each individual verb that https://github.com/Winetricks/winetricks/commit/caa28d1af97ddd3d7b3e76ca7f51fb85fe1ce7eb affected, and these two indeed fail, so this patch reverts the change for those two.
> dinput8, dsound: Don't try to register native DLLs.

- src/winetricks
Use the built in InstallShield silent mode of the installers instead of trying to script UI interactions with autohotkey.
This makes the installation faster and more reliable when doing unattended installations.
> icodecs: Make unattended installation faster and more reliable

- src/winetricks
Update was requested by @LeXofLeviafan on https://github.com/Winetricks/winetricks/issues/1158
Sourced based on https://www.virustotal.com/gui/file/6718308e10a45176155d0ecc8458bd3606308925b91f26a7d08c148cf52c9db3/details
Signed-off-by: Jacob Hrbek <werifgx@gmail.com>
> adobeair: update checksum for 32.0.0.125

- src/winetricks
I haven't updated `files/verbs/all.txt` and the like, since AFAICT they're automatically generated with `src/release.sh`.
I'm not sure whether keeping pywin32 installed together with base python is necessary, but I'm keeping it for compatibility with python26.
pywin32 is now on github, so fetching the latest version from there. See the notice at sourceforge:
https://sourceforge.net/projects/pywin32/
Tested both with and without W_OPT_UNATTENDED=1.
> python27: new verb

- src/winetricks
Mirrored from ie8 fix by Zebediah Figura.
> ie7: Override ieproxy to native and copy it to system32.

- src/winetricks
* Gitlab doesn't provide a way to determine an artifact
commit version. So do delete/update the currently cached archive
- but only when the verb is forced. Obviously a more elegant
solution is required!
* fixes: https://github.com/Winetricks/winetricks/issues/1270
* update Vulkan requirements
>  d9vk_master verb: pre-delete cache archive

- tests/self-update-test
The broken commit didn't fail for me on my pesronal repo when testing; so I'm PRing this to make sure it works for main repo.
> tests/self-update-test: use oldest commit instead of previous commit

- src/winetricks
Fixes #1310 
wsh56 was deprecated in https://github.com/Winetricks/winetricks/commit/9dc7daac7dfe51f59e3886e39d3b61cd1f933720
> jscript: call wsh57 as wsh56 is deprecated.

- src/winetricks
Add button click to irfanview automatic installation script.
This sets the option to generate start menu icons because there is no other way to start it from gui.
> Irfanview start menu icons

- src/winetricks
I installed dotnet46 without -q and checked with winetricks --verify dotnet46. (Although that just said that dotnet46 was already installed, not sure if that's the expected behaviour)
> Add wine versions for bugs that have been fixed

- src/winetricks
Fixes: https://github.com/Winetricks/winetricks/issues/1321
> helper_dxvk_d9vk(): fix invalid dll override handling, on BSD

- src/winetricks
> opensymbol: Update mirror

- src/winetricks
Current mirror is down, this attempts to use webarchive.org's mirror 
from oldapps.com
Fixes: https://github.com/Winetricks/winetricks/issues/1336
Relevant: https://github.com/Winetricks/winetricks/issues/1336#issuecomment-535097786
Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>
> ie6: Updated mirror using webarchive.org

- src/winetricks
Added `-f` option to --force argument to get WINETRICKS_FORCE, because 
~~i'm lazy~~ it's wasting time writing.
Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>
> winetricks_handle_option: Added -f option to WINETRICKS_FORCE

- src/winetricks
When the `winetricks_annihilate_wineprefix` function removes shortcuts associated to the prefix under the XDG user-specific data directory, it starts at `$XDG_DATA_HOME/applications/wine`. With Wine 4.9 (and other unspecified versions) shortcuts are actually rooted at `$XDG_DATA_HOME/applications`, adopting the naming pattern `wine-extension-<suffix>.desktop`. Besides leaving stray shortcuts, the `wine/` folder may well never be created, causing the `find` invocation to output: `find: ‘[...]/.local/share/applications/wine’: No such file or directory`. This change aims to remedy the problem by finding files from one level up.
> annihilate: Include prefix shortcuts rooted at $XDG_DATA_HOME/applications

- src/winetricks
Previously dlls/settings weren't setting this. This causes a problem if
prefix=foobar is used for a dll; ~/.wine (or $WINEPREFIX) would get used
for winetricks_is_installed() instead of $HOME/.local/share/wineprefixes/$cmd
This broke things when the WINEARCH didn't match.
> w_do_call: always set the wineprefix

- src/winetricks
* winetricks.bash-completion: requries that short options are
listed before long options, in the BASH case statement entries.
This is due to simplified regex handling employed in the
bash-completion script.
* fixes a regression introduced by:
f40b4655f8f3951730b271ee02ebe9dbcc619ecc
> reorder -f|--force options, required by bash-completion script

- src/winetricks
Since bug 48347 is IMO a "wontfix" here`s workaround to still get wmp10 installed
> wmp10: workaround for broken installer wmp10

- files/verbs/dlls.txt
- src/winetricks
Add a new dxtrans verb, which extracts dxtrans.dll from downloaded WindowsXP-KB936929-SP3-x86-ENU.exe, copies it to system32 and registers. That dll is required by Windows Movie Maker 2.0 installer and missing in Wine by default.
Just checked: after my chages, installing MS dxtrans works correctly.
I preferred using already implemented XPSP3 helper instead of adding a new DirectX 8.x helper, because it is a bit hard to find original DirectX 8.2 XP installer in the Web, since it was removed from the MS website.
Also I doubt about publishing year: should I use a year when the file has been changed last time or a year when that DirectX version has been released? :thinking:
> new verb: dxtrans

- src/winetricks
enables remapping of modifier keys for mac keyboards. See Wine Bug 35351
This is only applicable in Wine >= 3.17 and when using macdriver=mac
> new setting: mackeyremap

- src/winetricks
DXVK 1.5.2 was released hours ago. This PR adds a verb which allows installing the latest DXVK release.
> New verb: dxvk152

- src/winetricks
I fixed the bug in issue #1479 from myself.
Fix non-zero exit code when breadcrumbs file can't be found. This should not cause exit 1.
It was indeed a PITA, but I want to get it fixed.
Regards,
Melroy van den Berg
> Fix non-zero exit code (while expecting exit 0)

- src/winetricks
From <https://bugs.winehq.org/show_bug.cgi?id=48218>. Either the application
or the .NET runtime tries to load mscorwks.dll from a fixed path which
doesn't contain mscorwks.dll, causing the builtin stub to be loaded in its
stead instead of returning failure.
Tested with "winetricks-test dotnet", no failures.
> dotnet: Override mscorwks to native.

- src/winetricks
Currently tested with Resident Evil 5/6 in 64-bit prefix with proton.
> wmp11: add new verb

- src/winetricks
There is a much newer version of gdiplus for Windows XP available from the internet archive (2009 instead of 2004). Playonlinux has been using the newer version for a while: https://www.playonlinux.com/en/app-518-POL_Install_gdiplus.html
This PR updates `load_gdiplus_winxp` to load the newer version of gdiplus.
> load_gdiplus_winxp: update to newer winxp gdiplus

- src/winetricks
https://www.microsoft.com/en-us/download/details.aspx?id=9774
The 64bit .exe (msi) also includes the 32bit dlls
```
msxml6
├── 32
│   ├── msxml6.dll.86F857F6_A743_463D_B2FE_98CB5F727E09
│   ├── msxml6.msi
│   └── msxml6r.dll.86F857F6_A743_463D_B2FE_98CB5F727E09
└── 64
├── msxml6.dll.1ECC0691_D2EB_4A33_9CBF_5487E5CB17DB
├── msxml6.dll.86F857F6_A743_463D_B2FE_98CB5F727E09
├── msxml6.msi
├── msxml6r.dll.1ECC0691_D2EB_4A33_9CBF_5487E5CB17DB
└── msxml6r.dll.86F857F6_A743_463D_B2FE_98CB5F727E09
```
For some reason the .msi file doesn't finish installing
```
0009:err:msi:ITERATE_Actions Execution halted, action L"SkipInstallCA" returned 1603
```
So i decided to just extract and copy the files to their proper locations..
I'm not sure i have an app that uses msxml6 but testing with the latest …
> msxml6: update to service pack 2

- src/winetricks
The referenced D9VK repository for this verb is achieved and unmaintained, as it was merged with DXVK. It no longer receives the latest builds of DXVK.
> Fix dxvk_master verb downloading from d9vk repository

- src/winetricks
@soredake can you try this with proton? I made some changes to allow installing this on wine-devel, and I want to make sure it doesn't break things for proton.
> wmp11: extract the main installer and then run subinstallers

- src/winetricks
This should fix #1517. (except for the request for newer speechsdk version, but I think that could/should be a new issue)
I also removed the W_32BIT_DLLS variable as it was the same as W_SYSTEM32_DLLS and only used in speechsdk.
I added a warn for 64bit as it seems only a 32bit dll is installed.
If any of the above is not desirable, let me know.
> Various speechsdk fixes

- src/winetricks
> prntvpt: Copy correct dll for win64

- src/winetricks
The renderer key was introduced in [wine-3.17](https://source.winehq.org/git/wine.git/commit/723e62ab9956288e241c9a2956eaf9d2c955161e) and the DirectDrawRenderer key was removed in [wine-5.1](https://source.winehq.org/git/wine.git/commit/6e515efb715824a4811c40ee3833d48e460d5e67).
Fixes #1542
> ddr: fix registry key for newer wine versions

- src/winetricks
@austin987 I haven't finished, but this is what I have now, the rest will look similar. The reason I'm creating this draft PR now is so that, if you have time, you can have a look at the approach, so I don't have to rework more than necessary.
Some notes:
- I'm not completely sure what installed_file{1,2,etc} are for, but the old wiki seems to suggest they're used to check if a verb is already installed. This will be a problem for the mfc verbs, since the vcrun* verbs use the mfc dlls as installed_file1. Am I correct here and if so, what would be a good way to fix this?
- I opted against using a separate helper function since it didn't seem worth it, but if you know some more ways to avoid code duplication a little, let me know.
Fixes #1455
> Add separate mfc verbs

- README.md
When you run the specified installation script in bash, the evaluated `mktemp -d` statement appears in the update_winetricks file. So the update_winetricks file contains e.g. `cd "/tmp/tmp.htySgyRnuY"`.
Such a folder may no longer exist, e.g. the next time you start your computer. I think the goal was to create a new temporary directory every time. For this to happen, the statement must be escaped.
> readme: add missing escape backslashes in installing&updating scripts

- src/winetricks
When a WINE64 variable is already set, the user probably has some real serious intentions about what it is. Do not eff with it even if $WINE ends with 64. Fixes #1454.
> Don't force a WINE64 variable when one is already set

- README.md
I noticed that the link now 404s, corrected by searching the package repo for `winetricks`.
> README.md: Update link to Arch package

- src/winetricks
- src/winetricks.1
Add missing fonts category to the usage string. Synchronize manpage
commands section with the usage string.
> usage,man: add fonts category and synchronize

- src/winetricks
Microsoft released a new Visual C++ version a few days ago, this updates the expected sum to match the new file.
> Update vcrun2019 sha256 hash

- src/winetricks
Simple refractory to use TRUE and FALSE instead of 0 and 1
This will make the logic flow better and cause less confusion with other definitions of other languages.
> Use TRUE and FALSE instead of 0 and 1

- src/winetricks
Microsoft has removed these executables. I opted not to use web.archive since it was really slow for me, but found another download that had the same checksums.
Fixes #1597
> win7sp1: update urls

- src/winetricks
Update to latest release of cnc-ddraw (Feb 4, 2020). See https://github.com/CnCNet/cnc-ddraw/releases.
> cnc_ddraw: update to 1.3.5.0

- src/winetricks
Microsoft has updated the 2019 redist packages.
This updates the checksum to match the new files.
> Update vcrun2019 hash

- src/winetricks
RPG Maker (RPG Tkool) XP/VX/VXAce games need `gmdls`, `dmsynth`, `dmusic`, `dmband`, `dmime`, `dmstyle`, `dsdmo` and `dsound` for MIDI playback, but after installing them MP3 playback needs the "Feb 2010" version of `quartz`: Built-in version doesn't play MP3 files properly with native `dsound`, and "[win7sp1](https://github.com/Winetricks/winetricks/commit/20ec914d2025d0d3aec3c33cc75a276d53336db9)" version doesn't work.
So I really need the "Feb 2010" version of `quartz` for RPG Maker games.
> quartz_feb2010: new verb

- .travis.yml
This PR adds CI support for the IBM Power Little Endian (ppc64le) architecture. The idea is to ensure that the builds on this architecture are continuously tested along with the Intel builds (amd64) as this is part of the ubuntu distro on that architecture as well and detecting (and fixing) any issues or failures early would help to ensure that we are always up to date. Since ppc64le doesn't have shellcheck by default, installing it before_install
> Add travis job for ppc64le. Install shellcheck

- src/winetricks
A stub for dplaysvr.exe was added in [this commit](https://source.winehq.org/git/wine.git/commit/73afd2648c003fbddb657fc8a3f8f53a86754dcd), which started causing hangs when native directplay was installed. This PR fixes it. For reference, see [this bug](https://bugs.winehq.org/show_bug.cgi?id=50217).
> directplay: add native override for dplaysvr.exe

- src/winetricks
Fixes #1667 and fixes #1635.
To clarify commit 3, the bug mentioned doesn't seem to be the reason why it has to run in XP mode anymore. In Win7 it will refuse to install ucrtbase.dll if it's missing, but it won't replace it if it's not removed before the installer is run.
I split the commits into chucks that made sense for me, but feel free to request more splitting/changes.
> vcrun improvements

- src/winetricks
Stubs for these dlls were adding in the staging patchset dxdiag-new-dlls. This was causing issues with Total Annihilation and Moonbase Commander, so installing the native versions in the directplay verb seems like a good idea.
> Directplay improvements

- src/winetricks
- api-ms-win-crt-convert-l1-1-0
- api-ms-win-crt-environment-l1-1-0
- api-ms-win-crt-filesystem-l1-1-0
- api-ms-win-crt-multibyte-l1-1-0
- api-ms-win-crt-process-l1-1-0
- api-ms-win-crt-string-l1-1-0
- api-ms-win-crt-utility-l1-1-0
> vcrun2015: add missing CRT API DLL overrides

- src/winetricks
This is necessary because otherwise the Store and Library tabs will be black. It "works" with libglesv2 diabled. I say "works" because it's functional enough to be useful, but still suffers from flickering/repainting issues.
> steam: disable libglesv2

- src/winetricks
> Update DirectX9 urls

- src/winetricks
The _usetakefocus=disabled_ verb is captured by pattern _*=disabled_ at row 23136, as I have reported (#1699).
The proposed solution replaces the argument values _enabled/disabled_  by _y/n_, removing the conflict.
I was in doubt about keeping backward compatibility by preserving the _usetakefocus=enabled_, then allowing two ways of enabling the setting, but I have opted for the "cleaner" approach.
> Replace usetakefocus argument values

- src/winetricks
@austin987 
I'd probably like to drop the verb:
`dxvk_master`
as it's clear that Joshua isn't really bothered about resurrecting his CI builds.
I'm not sure this verb is terribly useful now anyway...
**dxvk** is very stable these days anyway!
Is OK just to nuke it?  :-)
Bob
> Update dxvk verbs

- src/winetricks
- tests/winetricks-test
* fixes: https://github.com/Winetricks/winetricks/issues/1638
> dxvk_master: delete verb - no longer supported Upstream

- src/winetricks
> Manually install ucrtbase in vcrun* verbs instead of deleting it

- src/winetricks
Wine doesn't create syswow64/drivers, since it has nothing to put there. On Windows gm.dls is one of the only things occupying syswow64/drivers.
As an aside, the version of gm.dls in system32 and syswow64 is the same on Windows (SHA1 matches).
> Fix installing gmdls in 64bit prefix

- src/winetricks
Apparently this switch has been around for a while, so we can be sure it's safe to remove the AHK script.
> steam: use /S instead of AutoHotkey for silent install

- src/winetricks
based on the [WINE documentation](https://wiki.winehq.org/MIDI), this setting adds the ability to easily specify the configured MIDImap device. since the device can be an arbitrary value, it didn't seem like the `key=val1,key=val2` pattern would work here so i came up with a solution based on an environment variable and `w_question`. let me know if you don't think this is appropriate for the scope of winetricks or if there's a better way to pass in arguments
> set_mididevice: new setting

- src/winetricks
1. restore broken prefix by extracting DLLs (set to 'native' override) from the IE bundle.
2. remove msctf.dll from being deleted DLLs list, otherwise IE8 installer skips the copying files step.
> ie8: Fix verb for recent Wine versions.

- src/winetricks
We discussed adding a verb to install the older WinNT 4.0 version of pdh.dll since it helps compatibility with some programs like VARA (part of Winlink / RMS Express).  I got the green light from austin987 to add it ( https://github.com/Winetricks/winetricks/issues/1579 ).  This is my first edit to winetricks, and I'm new to bash, so let me know if this implementation looks strange or isn't standard.
Note: I created an earlier pull request, but realized I had typos in it, so this is a new PR
> pdh_nt4: new verb

- src/winetricks
Newer than 9.14 is needed for Batman Arkham Knight to
render "Interactive smoke/fog". This will download and
install latest 9.19 version.
> Update PhysX version

- src/winetricks
The installer is very small, so shouldn't be an issue.
Fixes #1751, Fixes #1807
> msls31: use archive.org

- src/winetricks
After the introduction of SIP (OS X 10.11) DYLD_ environment variables are stripped.
See https://support.apple.com/en-us/HT204899
<br>
As `winetricks` is launched from a system provided utility DYLD_ variables will be stripped leaving them empty. 
`DYLD_FALLBACK_LIBRARY_PATH` used to provide additional library paths.
> workaround SIP DYLD_ environment stripping

- src/winetricks
This verb provides a workaround for [Wine's oleacc bugs](https://bugs.winehq.org/buglist.cgi?component=oleacc&list_id=749105&product=Wine&resolution=---). I can confirm that the NVDA screen reader works quite decently with the native DLL!
Download description page: https://www.microsoft.com/en-us/download/details.aspx?id=21596
> msaa: new verb

- src/winetricks
This PR fix some problems when a wine prefix contain symlinked dlls in its system32 or syswow64 folders.
* Add `w_try_cp_dll` function. This function will detect and remove symlinks before copying.
* Replace all `w_try cp` calls for `w_try_cp_dll` when they try to copy dlls into W_SYSTEM32_DLLS or W_SYSTEM64_DLLS.
wmp11 package:
* Remove dlls from both dll folders.
* Adding missing dlls.
Resident Evil on steam can now run. Tested with glorious eggroll proton. This also fix problem #1648.
There is probably a lot of other packages that will try to install stuff over symlinked dlls. That will cause one of 2 problems: Getting a permission denied if the target of the symlink is in a system folder without write access for the user. Or if the wine installation is writable by the user, its dlls …
> Fix problem with symlinked dlls and fix wmp11 package.

- src/winetricks
Microsoft .Net 3.5-sp1 and later moved to dotnet.microsoft.com
The following verbs urls & checksums were all updated.
- dotnet46 (checksum didn't change just url)
- dotnet462
- dotnet471
Closes https://github.com/Winetricks/winetricks/issues/1853
> dotnet*: Update urls

- src/winetricks
The hash seems to have changed for vstools2019.zip
> vstools2019: update hash

- src/winetricks
Detects when KDE Plasma when currently running and checks if kdialog is installed first before zenity and , if available, chooses kdialog over zenity for desktop environment consistency.
Also stops calling alternatives a "poor substitute" and opts to call them "a substitute" instead.
> Solves Issue #1654 - Use kdialog instead of zenity in KDE Plasma, When Available

- src/winetricks
When using winetricks without any argument on KDE, this error happens:
```
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
Using winetricks 20210206-next - sha256sum: 9e9e998ff3412e991b36dc5d543edcffc83a16be88280b6d78ac67220d11ccb1 with wine-7.0 (Staging) and WINEARCH=win64
/usr/bin/winetricks: 3539: test: KDE: unexpected operator
winetricks GUI enabled, using none 
```
Because this is a simple fix, I am creating a pull request instead of an issue.
> Fix for 3539: test: KDE: unexpected operator

- src/winetricks
Since no new files are created when installing version 9.21.0713 over
previous 9.19.0218, use sha256sum function to check if 9.21.0713 is
installed.
This solves https://github.com/Winetricks/winetricks/issues/1843
> Update NVIDIA PhysX version

- src/winetricks
vcrun2019 and Linux repos that are slow to update winetricks can benefit from this change.
Linux newbies no longer need to jump through hoops to fix a program or game that won't run in wine due to a missing dependency that refuses to install because it failed the SHA256 check.
> winetricks: Add confirmation prompt to install verb even if SHA256 check fails

- src/winetricks
```
Executing cd /home/Alexander88207/.wine/dosdevices/c:/windows/temp
Executing tar -I zstd -xvf /home/Alexander88207/.cache/winetricks/vkd3d/vkd3d-proton-2.6.tar.zst
tar: Error inclusion pattern: Failed to open 'zstd'
```
with `--use-compress-program=unzstd` it works and afaik it should still work on linux too.
> Use tar --use-compress-program=unzstd to make it work on FreeBSD too.

- src/winetricks
Remove symlinks that target the $HOME directory (or subdirectories
of this directory) within the current WINEPREFIX C:\users\<user>
directory.
Test for symlinks which are in subdirectories of the current
WINEPREFIX.
Ignore symlinks to files (as before).
Closes: #1905
> isolate_home: correctly handle subdirectory symlinks to $HOME

- src/winetricks
w_askpermission w_info w_warn w_warn_cancel: update functions
Use 'printf' instead of 'echo' command to ensure escape sequences are
consistently interpreted, under any shell.
> winetricks: interpret backslash escape sequences for console messsages

- src/winetricks
This was resolved in 4.20 Julliard only closed the bug out in 5.4.
Here's the output when this fix it applied.
```
Executing mkdir -p /Users/gcenx/Applications/Wineskin/Origin.app/Contents/SharedSupport
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
Using winetricks 20220411-next - sha256sum: f6d0b88306a3794d4a60cc9344504499aeaf39ad1dd589c8d3e77110e8963c50 with wine-6.0.2 (WineskinCX 21.2.0) and WINEARCH=win64
Executing w_do_call d3dcompiler_43
Executing mkdir -p /Users/gcenx/Applications/Wineskin/Origin.app/Contents/SharedSupport …
```
> d3dcompiler_43: correct bug 24013

- src/winetricks
vcrun verbs should also use `w_try_ms_installer` as these installers pass these exit codes.
Also added handling status 236, this being used to indicate a newer version of the dlls already exist. Seen this one after installing Origin then attempting to install vcrun2010.
> Vcrun use w_try_ms_installer & handle status 236

- src/winetricks
The `origin` verb will install the Origin client and exit cleanly after install and can also be installed silently.
Darwin requirements need to be higher due to most being on more modern versions of macOS (10.15+) so forced to use a winecx variant where Origin _doesn't_ function until the more recent WineCX21.x based builds (Wine-6.0+) due to some missing thunks within `wine32on64` related functions
OriginSetup automatically installs the listed vcrun installers so added those to ensure they get registered correctly, `d3dcompiler_47` is used by the Origin client.
The override of `gameux` being set to disabled made games correctly register when left enabled games will goto 100% and then not show as playable without rebooting Origin where having this disabled makes games register without …
> origin|originupdater: new verbs

- src/winetricks
The old code only works with --no-clean.  When cleaning is turned on, the unpacked VCExpress directory will be blown away as soon as `w_call` is called.
> Fix vc2010express

- src/winetricks
Origin already ships this dll
wine-6.3 and later prefer native dlls, as Origin bundles this dll it shouldn't need to be installed on later versions of wine.
> origin: Only install d3dcompiler_47 below wine-6.3

- src/winetricks
The aim of this application is to hook games allowing even older games to support windowed mode or simply get working on modern versions of windows, this also helps getting some games working within wine.
Lutris has many scripts that make use of this and is also good for getting legacy titles working again on macOS Monterey that worked on prior macOS versions (using winecx/crossover)
> dxwnd: new verb

- src/winetricks
I remember a number of online games require this or they get un-synced.
GE-Proton bundled protonfixes uses a custom version of vcrun2019 that uses this installer as it's the final version that still bundled ucrtbase
> ucrtbase2019: new verb

- src/winetricks
- workaround for the constant crashing from igoproxy(64).exe
- vcrun2013 as I'd forgotten this
- w_warn to ensure in-game origin gets disabled (many games crash when it's enabled)
Should wait for #1966 to be merged to ensure a new version of ucrtbase is usable.
> origin: Connect overriders to Winehq bugs

- src/winetricks
Since I'd force pushed to https://github.com/Winetricks/winetricks/pull/1961 I can't re-open it.
Tested with the following builds WineCX22 (wine-7.7 upstreams wow64), WineCX21 (wine-6.0 wine32on64) and upstream wine-7.18 (stock wine, wine64)
> Wow64 tweaks

- src/winetricks
Steam Login UI when `libglesv2` is disabled
<br>
Steam Login UI when `libglesv2` isn't disabled
<br>
Tested this on;
- wine-7.0
- wine-7.19
- wine-crossover-22.0.1 (wine-7.7 with WoW64)
<br>
When using `-noreactlogin`
<br>
<br>
Bug 49839 is macOS only, shows the needed launch commands on macOS.
> Steam Login UI black screen fix (reactlogin)

- src/winetricks
Remove deprecated files as of release 2.0
Tested on local machine
Changes compatible with verbs utilizing older dxvk versions
Fixes #1980
> dxvk: Fix verb checking for files deprecated as of release 2.0

- src/winetricks
src/winetricks:11341:1: E003 Indent not multiple of 4
> tests/shell-checks: fix a bashate indentation issue

- src/winetricks
Installing WMP11 in a 32bit prefix will fail as is.
> Correct typo for wmp11.exe in 32bit prefixes

- src/winetricks
This verb adds TLS 1.1 and TLS 1.2 support for IE 8, configurable through the UI in *Tools : Internet Options : Advanced*.
Changes to the configuration affect the registry value at:
*  `HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\SecureProtocols`
Any configuration made prior to installing this verb influences the initial value, so the verb doesn't concern itself with modifying the registry to enable the new protocols without user interaction.
Also, the UI (IE 8 menu bar) isn't visible with the `Windows 7` setting, so this verb doesn't issue a final `w_set_winver 'default'` invocation. FWIW the menu bar isn't the only part of IE's UI that breaks with that setting.
**Before enabling both protocols**
**After enabling both protocols**
**Added:** As discussed in #1593 …
> ie8_tls12: new verb

- src/winetricks
The version in this method was still old, which caused breakages when installing components like allcodecs.
> autohotkey: bump to 1.1.36.01 in w_ahk_do()

- src/winetricks
The description column is too wide. This commit attempts to shorten it a bit.
The problem looks as follows:
With this PR the year and publisher columns will not appear but the description column is shorter now.
> zenity: Limit description length

- src/winetricks
While at it, I tried to find and fix more issues with shellcheck... but the script gave no output; so I assume it's alright?
Tested and reproduced with the `dash` POSIX shell and `WINE="/path/with spaces/wine"`
> Fix w_store_winver when $WINE contains spaces

- debian/control
- src/winetricks
policykit-1 is a transitional package depending on a new pkexec package since Debian 12 (bookworm)/Ubuntu 22.04 (jammy).  Keep the former dependency for trivial backportability for now.
> debian/control: add alternative dependency on pkexec next to policykit-1

- src/winetricks
Two small fixes to `winecmd` and `shell` commands:
* Do not use `-e` parameter when launching terminal emulator if no command
was provided. This is the case for `shell` verb, which does not provide
any predefined command and should just launch the terminal.
In addition, pass the `-e` argument as one quoted string. Some terminal emulators only accept one value, while others consume all parameters following the option. Using a single string works with both.
* Fix `winecmd` launch. `winecmd` seems to be the intended command here. `cmd` only installed an
application of the same name without launching it.
> Fix 'shell' and 'winecmd' commands

- src/release.sh
This is now necessary to get a bit-by-bit identical tarball. Closes Issue: #2024
> src/release.sh: Use external gzip to create local tarball

- src/winetricks
The new version was released because of binary compatibility with wine v8.3.
Extend the current galliumnine verbs to handle the incompatible combinations.
> galliumnine09: new verb

- src/winetricks
Please let me know if I overlooked anything or otherwise did something wrong; I _**think**_ I did this right but I'm not sure.
dxvk-nvapi is (mostly) a replacement for the physx verb, because it supports physx calls, but I didn't want to touch the physx verb since I'd be unsure of the potential impact; though, it is pretty safe to say that the physx verb is otherwise deprecated (but do correct me if you know more than I do).
> Issue #1983: Add a dxvk-nvapi verb

- src/winetricks
There's obviously a lot more room for improvement for winetricks/osx, but as a first step..
@Gcenx could I get your thoughts?
> winetricks_set_wineprefix: warn user if running on OSX m1/m2 and Rosetta2 is not installed

- src/winetricks
As it stands this code tries to execute the non-existant file `""` which fails with a confusing error, but the install works correctly when the filename is specified.
> Add missing filename to `dotnet6` verb

- src/winetricks
Version 2.9 introduced a change regarding the bundled D3D12 DLLs.
Reported by: @AlfredoRodda in #2077
> vkd3d: Add d3d12core

- .github/workflows/install.yml
- .github/workflows/shell-checks.yml
- .github/workflows/update.yml
- Add a name to the workflows, so GitHub does not just show the file.
- update the actions/checkout version from v2 to v3 so the actions warning goes away
> Add name to workflows and update checkout version

- src/winetricks
This gets Origin working again, since EAapp doesn't really work without patches it's good to have Origin as a fallback.
This also fakes EAapp being installed so EALink can be used to launch EA games via Steam.
> origin: Add workaround

- src/winetricks
- src/winetricks.1
New options were added to winetricks over time, but the manpage hasn't been updated. This commit brings it up-to-date.
`games list` is removed because there are no longer any games verbs. Also references Github Wiki discussed in #2094  as Winetricks documentation.
> Update manpage and help with latest options

- src/winetricks
mfc140 download the different version of VC2015 than vcrun2015. Changed URL and checksum.
> Update mfc140 to load the same version of VC2015 as vcrun2015

- src/winetricks
Follow-up to #2037. While that PR fixed `-e` parameter for some terminals such as `xterm`, the single string passed as argument was not escaped properly, causing `winecmd` to fail if `WINE` contained a space.
Fix this by single quoting each argument and concatenating them together. This is a bit tricky in POSIX sh without `printf %q`, but seems to work fine with the code suggested by ShellCheck for SC3050.
I went ahead and tested the fix with every terminal except for `Terminal`, and it should work properly in all cases now.
> Fix `winecmd` when Wine path contains spaces

- src/winetricks
> icodevs: override ir50_32 as native,builtin before trying to regsvr it

- src/winetricks
Fixes issue #2118, while still pulling fonts from the original mirror (at their new URLs).
> Update corefont urls to new locations on mirror.

- src/winetricks
Directly download d3dcompiler_47 dlls instead of extracting them from Firefox installers.
> d3dcompiler_47: Download from mozila github repo

- src/winetricks
`od` needs the actual path to the binary. This PR fixes #2143.
> Ensure `winetricks_get_file_arch` gets full paths

- src/winetricks
Bump .NET 7 Runtimes to 7.0.13.
Additionally use official SHA512 sums provided by the dotnet website.
> dotnet7+dotnetdesktop7: Bump to 7.0.14

- src/winetricks
- Update `file1` it's not been `SteamInstall.msi` in years.
- `-noreactlogin` argument has long been removed from Steam stable branch
- `-no-cef-sandbox` was replaced by `-cef-disable-sandbox`
> steam: Update workarounds

- src/winetricks
Use win7sp1 instead of winxpsp3, it easily provides both 32 bit and 64 bit DLLs, with the added benefit of likely being newer.
> crypt32: Install both 32 and 64 bit DLLs

- src/winetricks
We should not be removing mscoree.dll in all dotnet* installs because it could have been placed by the dotnet40 verb, which would cause subsequent dotnet* verbs to break dotnet40. The deletion should instead only happen when the native dotnet is detected. We continue to remove the registry keys in any case, though, since they are only relevant to the native DLL.
Closes #2072
> Fix remove_mono breaks dotnet40 on subsequent dotnet* installs

- src/winetricks
When using [wget2](https://gitlab.com/gnuwget/wget2) in place of wget 1.x (which I don't think is a good idea in the first place because the compatibility is not 100%, but let's assume our software choices have led us to this timeline anyway), web.archive.org URLs don't download as expected because apparently wget2 sends an HTTP Accept header that the site interprets to not send the file but instead send some HTML referencing the file. This causes an issue in the Lutris Flatpak when using fallback archive.org URLs because the Flatpak runtime includes wget2: https://github.com/flathub/net.lutris.Lutris/issues/365#issuecomment-1741590369.
The suggestion was to explicitly set the Accept header to accept any content type instead of preferring HTML …
> Improve compatibility with wget2 (mostly for web.archive.org URLs)

- src/winetricks
By default, curl doesn't handle 4xx and 5xx specially, it will just download the body of the error response. The `--fail` parameter is necessary to make it exit with a nonzero status code so download errors don't get silently swallowed.
> Make curl not swallow errors

- src/winetricks
Closes: #2163 
Now the sum is a sha256 sum, if you go to the URL you actually get a file and not an error.
> Fix dotnet7

- README.md
There's a Makefile for Winetricks that works perfectly well for installing it, and is probably easiest way to install the latest stable Winetricks release, satisfying #1192
> Explain how to use Makefile to install stable release

- src/winetricks
Otherwise it fails due to not receiving a response:
Would you like to replace the existing file:
Path:     C:\windows\syswow64\ddraw.dll
Size:     1053865 bytes (1030 KiB)
Modified: 2024-01-28 17:55:30
with the file from archive:
Path:     ddraw.dll
Size:     316928 bytes (310 KiB)
Modified: 2023-01-16 21:18:30
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit?
Archives with Errors: 1
> 7zip in w_try_unzip needs -y flag to autoconfirm

- src/winetricks
This adds a verb for https://github.com/otya128/winevdm
This is a fork of winevdm (using an emulator) with way better compatibility. Since it needs a bunch of overrides, I do think this could be useful.
> Add otvdm verb

- src/winetricks
In the latest release I got a sha256 mismatch error, so I downloaded the files and updated the sums
(ofc there lowercase here, stupid windows)
> Update vcrun2022 sha256 sum

- src/winetricks
> origin: Updated workaround to v3

- debian/control
- src/winetricks
See commit messages for details, trivial update.
> Update debian package recommendations

- src/winetricks
Wine no longer has a builtin openal32.
> alldlls=builtin: remove openal32

- src/winetricks
This adds support to allow users to `export W_NO_WIN64_WARNINGS=1` for toggling off win64 warning messages (this new way is in addition to the file-based logic from [an earlier commit](https://github.com/austin987/winetricks/commit/01de762dfa656471cee0df3f6508b82a07de9117) and so should not break any existing setups).
This proposal and the advantages were previously discussed in the comments of issue #1730 but for convenience, those were:
> 1. Allows users to _completely_ suppress the message (including echo statement from touched file) if they _really_ want to
>
> 2. Allows to set an environment variable for a terminal session but not forever (or alternately could use `.bashrc` or equivalent for all terminal sessions)
> 
> 3. Reduced number of I/O hits checking for a file (I know it is …
> minor update to win64 warning messages to support toggling via env var

- src/winetricks
Hi, it's my first PR here. Added a verb for easily enabling the experimental Wayland driver in Wine 9.0+.
- Also usable for the same purposes as macdriver; deprecated macdriver
- Has Ukrainian title and (new language) Russian title
- Fixed settings with value =default being interpreted as DLLs
That last one was also affecting another setting, `videomemorysize=default`.
This setting seems important to me, so I put it at the top of the "desktop" category. Maybe it should be renamed to "graphics"? Or maybe it doesn't matter much, looks like those categories are just comments.
Note that the "wayland" option actually sets the driver to "wayland,x11", so Wine will try Wayland first, but should fallback to X11 if it's not available.
> New verb "graphics", for enabling Wayland driver

- src/winetricks
Workaround case where wine and related binaries are in /usr/bin, but wine64 is only in Wine's bindir (as in Debian wine 8.0~repack-4). Use /usr/bin/wineboot (which is a symlink in Debian packaging) to figure out the bindir, because /usr/bin/wine is a wrapper script in Debian.
See discussion in https://bugs.debian.org/1031649.
I'm not sure if this already should be added in Winetricks, probably this depends on the next set of Debian Wine packages. For now I applied this patch in Debian.
Tested with the deb packages from Debian wine 8.0\~repack-2 and 8.0\~repack-4, and Winehq winehq-staging 8.2~bookworm-1.
> Workaround missing /usr/bin/wine64.

- src/winetricks
There are 2 general issues related to this fix, each handled in a separate commit:
winetricks: display messages for users to stderr
winetricks_get_file_arch: try workaround for wrapper scripts
winetricks_set_wineprefix: warn if binary arch is unknown
Please have a look at the detailed commit messages. E.g. not all of the stderr stuff is needed.
Feedback welcome!
3 open questions:
1. Is my readlink implementation sufficient?
"readlink -f" is not working on MacOS < 12.3
(https://apple.stackexchange.com/questions/464136/which-macos-version-introduced-readlink-f)
Alternatives are:
(See https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac)
- greadlink (extra package, in /usr/local/bin/)
- perl -MCwd=abs_path -le 'print abs_path readlink(shift);' …
> Fix architecture detection mechanism for wrapper scripts

- README.md
This PR changes the README's Debian install instructions. It removes the existing link to the unstable Debian package, and replaces it with a link where user the user can first choose their Debian version. This change helps prevent typical users from borking their systems (see below).
The [`README.md`'s Debian install instructions](https://github.com/Winetricks/winetricks/blob/master/README.md?plain=1#L20) link to winetricks within Debian's sid (unstable) package list. This is fine if someone downloads the winetricks `.deb` and installs manually, but at the download page the Debian site actually advises against this:
> If you are running Debian, it is strongly suggested to use a package manager like [aptitude](https://packages.debian.org/sid/aptitude) or …
> Update README's Debian install instructions

- tests/shell-checks
Since `set -e` is set this causes the script to exit immediately if a command fails..
So if shellcheck or bashate aren't available on path, `w_die` is never hit.
However if we pipe in true ensuring that command never "fails", we will actually hit `w_die` and the correct error is displayed.
> tests/shell-checks: Fix detection of bashate and shellcheck

- src/winetricks
This release fixes issues with non-english Wine prefixes and custom program files locations, as it resolves to environment variables instead of a hard coded string.
The lack of a change to the SHA hash for profile.ps1 is due to there being no changes for that file.
See the upstream changelog and code here: https://github.com/ProjectSynchro/powershell-wrapper-for-wine/releases/tag/v2.1.1
> powershell: Bump version of powershell wrapper

- src/winetricks
Fixes https://github.com/ProjectSynchro/powershell-wrapper-for-wine/issues/2 which fixes installing the EAC service in the RSI Launcher, as well as issues parsing arguments when using powershell commands inline.
> powershell: Bump version of powershell wrapper to 2.1.3.

- src/winetricks
Avoid a popup on WINEPREFIX updates, see https://bugs.winehq.org/show_bug.cgi?id=41727#c5
> dotnet:Fix 64 bit rundll32.exe pop-up window

- src/winetricks
With multiple verbs on the command line that retrieve the latest github release, the version from the first verb would be used for the second verb.
Delete the temporary version information file before fetching it to avoid using the previous contents.
> Fix multiple verbs getting latest github release

- src/winetricks
w_try_ar was needed for only one component, so I redid it and now this function is not needed - fewer dependencies
opensymbol font now downloaded from openoffice open github repo.
> redo opensymbol download, remove w_try_ar

- src/winetricks
It seems like the `archive.org` prefix is automatically added in the download function (on second try), meaning there shouldn't be a need for hardcoding the `archive.org` URL prefix.
I've tested a quick game installation using the downloaded EXE from the Microsoft servers & everything seemed to run fine.
Theoretically there could be another reason for the permanent  URL prefix - e.g. the setup file on the Microsoft servers changed at some point, no longer containing a working `ucrtbase.dll`. Play-testing Tarkov didn't reveal any issues with the dll..
edit: since the file is checked via `sha256sum` - this shouldn't be a concern either.
> Update URL for ucrtbase2019 to remove hardcoded archive.org prefix

- src/winetricks
This reduces the effort needed to make sure newer bugfixes make it into winetricks.
I replicated what was done in the dxvk and vkd3d verbs (which seems like removing the linkcheck on the w_download)
This also insures that the latest fixes are always grabbed (downstream projects don't need to pull winetricks constantly)
Let me know if there's a better way you'd like me to do this.
> powershell: Switch to w_get_github_latest_release

- src/winetricks
Updated 7zip to 24.09 and added arch bits conditional installation for win32 and win64
Better implementation of my attempt of https://github.com/Winetricks/winetricks/pull/2302 that doesn't require a new verb.
> Updated 7zip to 24.09 and added 7zip arch bits conditional installation

- src/linkcheck.sh
- tests/shell-checks
This fixes some issues with the link checker.
The commit 2bc95a12954f591acc463602bb45fcef791048c0 is reverted, but I can't find a reason why it should be a problem. Feedback is appreciated. 
- Check w_download_to
- Check only URL, not whole line
- Find lines that don't start with w_download
- Allow escaped $ in URL
- Escape '\$' to '%24'
CC #2199
> Refactored link checks

- src/winetricks
My `$USER` is `Dāvis` which contains Unicode and that causes `%AppData%` to be `C:\users\Dāvis\AppData\Roaming`
Currently `winetricks` doesn't work at all for me and fails with:
```
grep: (standard input): binary file matches
WINEPREFIX INFO:
Drive C: total 12
[...]
Registry info:
/mnt/Wine/system.reg:#arch=win64
/mnt/Wine/userdef.reg:#arch=win64
/mnt/Wine/user.reg:#arch=win64
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message ""
```
Reason is that because when `cmd.exe` pipes output it will use Windows Code Page which won't be recognized by …
> Fix Unicode $USER

- src/winetricks
Make it possible to set `WINE_BIN` and `WINESERVER_BIN` using environment variables outside Winetricks.
Winetricks performs a Wine binary bitness detection to print a warning. In some environments, such as Protontricks and Nix, the Wine executable is a wrapper that calls a binary that's located elsewhere. In those situations we want to provide the path to the binary that's only used for the check to avoid printing unnecessary warnings.
Closes: #2183
> Allow {WINE,WINESERVER}_BIN env vars

- src/winetricks
This reduces the run time of `winetricks allfonts` on Wine 9.22 on my Intel i7-1360P laptop from 5 minutes 19 seconds to 3 minutes 34 seconds, a 33% decrease.
> misc: don't initialize the Wine prefix before every single verb

- src/winetricks
- bump dotnet 8.0.11 to 8.0.12
- bump dotnet 9.0.0 to 9.0.1
> Bump dotnet 8 & 9

- src/winetricks
The winetricks_set_wineprefix function needs to run at least once even if WINEPREFIX was already set in the environment before running winetricks.
This partially reverts commit 21f2f7335db0c7de43a3b8cc9cc3ee416cd0cf1f.
Fixes #2325
> misc: replace NEW_WINEPREFIX with LAST_WINEPREFIX

- src/winetricks
PhysX installer bug has been fixed in Wine 9.10 according to Wine Bugzilla.
> physx: set good_version to 9.10

- src/io.github.winetricks.Winetricks.metainfo.xml
To make the metadata compatible with future AppStream standard version that uses the [developer tag](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer) instead of developer_name, but keep the original one for compatibility purposes.
@austin987 Feel free to review and merge. :-)
> Add developer tag to AppStream metadata

- src/winetricks
Install the 64bit version of the msvcp140.dll into the 64bit dll directory instead of installing the 32bit dll into the 64bit directory.
> vcrun2015: Install correct version of msvcp140.dll into 64bit directory

- src/winetricks
Fix for https://github.com/Winetricks/winetricks/issues/2344
> vcrun2019: Install correct version of msvcp140.dll into 64bit directory

- src/winetricks
All recent versions of wine support setting win10, it's the default for wine-10.0 plus many applications now require a minimum win10
> w_set_winver: change default to win10

- src/winetricks
This will be the final release IIRC, gallium nine will be removed from mesa3d in future
https://www.phoronix.com/news/Gallium-Nine-Deprecated
> nine: add 0.10 latest final release

- src/winetricks
Newer versions have support for HDR and the currently-available version (0.6.1) makes some games crash on launch.
> Add newer versions of dxvk-nvapi and a "latest" verb

- src/winetricks
Resolved by commit https://gitlab.winehq.org/wine/wine/-/commit/7ef35b33936682c01f1c825b7d1b07567a691c12 (wine-6.7)
> vcrun2015,2017,2019: Remove workaround for bug 50894

- src/winetricks
After changes to 7z verb this function became broken, this commit fixes the function.
> w_try_7z: Fixup

- src/winetricks
Fix sha mismatch for:
adobe_diged4
dotnet11sp1
dxsdk_jun2010
nook
procexp
sketchup
steam
utorrent3
vcrun2022
vstools2019
> Fix sha mismatch
