src/winetricks

Closes Winetricks/winetricks#489

Update takao-fonts download url

---

src/winetricks

Hi, please review and consider my request to update VLC to the latest version (2.2.1 2015) in winetricks.
Cheers!

Request to update VLC to 2.2.1(2015) in winetricks

---

src/winetricks

Hi, this is a patch for Firefox to version 39. If it looks good, please consider merging.
Thanks!

Update Firefox to version 39

---

src/winetricks

Download automatically from web.archive.org.

msxml3: Download from web.archive.org

---

src/winetricks

Download automatically from web.archive.org.

cabinet, dotnet30: Download from web.archive.org

---

src/winetricks

Hi, I've updated mozillabuild to version 2.0.0. Please take a look at this patch and if it's good, consider merging.
Cheers!

Update mozillabuild to version 2.0.0

---

src/winetricks

Install gm.dls which is required by some programs using DirectMusic.

Add "General MIDI DLS Collection" verb

---

src/winetricks

It's been updated so update hash.

Update hash for shockwave

---

src/winetricks

- 3M library ebooks
- Update to Kindle for PC

New and updated ebook verbs.

---

src/winetricks

* ipamona: Install IPAMona Japanese fonts
* fakejapanese_ipamona: Create aliases for Japanese fonts using IPAMona fonts

Support IPAMona Japanese fonts

---

src/winetricks

Replaced FTP urls to HTTP for corefonts

---

src/winetricks

This exact version is needed for the game Endless Legend.

Added a recipe for dotnet452.

---

src/winetricks

Hi Austin,
Seems I was bored and made those changes :)
copyright 2013 is for d4019f0494d8b8fbb0521334f165af290a4c3c8d
Have Fun!

German/English Fixes/additions/updates

---

src/winetricks

Update Chinese translation.
Update support for QQ 8.0, work around bug#39657 and bug#37680 for QQ and qqintl.
Update sha1sum for picasa39.

Update QQ, Picasa and Chinese translation

---

src/winetricks

And I think you accidentally removed the call to w_declare_exe when adding vcrun2008, so I added that back as well.

kindle: update to version 1.14.43019

---

src/winetricks

Preliminary Russian translation

---

src/winetricks

Add code editor hints

---

src/winetricks

Fixes #597 which was erroneously closed.

winetricks: Fix a vcrun2015 override

---

src/winetricks

Update QQ to 8.9.1

---

src/winetricks

after 0e3aa854f0237a9c62c0a5ff577d97e92f6c0283

qq: restore secure URL

---

src/winetricks

Please add this module, Wechat need it.

Add MS ole32 Module.

---

src/winetricks

Old source has been replaced with .NET 4.7

Updated .NET Framework 4.6.2 slim source

---

src/winetricks

https://web.archive.org/web/20140227220734/http://download.microsoft.com/download/1/E/5/1E5F1C0A-0D5B-426A-A603-1798B951DDAE/VS2010Express1.iso
sha256sum is a9d5dcdf55e539a06547a8ebbc63d55dc167113e09ee9e42096ab9098313039b

Update Winetricks - vs2010express ISO link

---

src/winetricks

Just fixed a typo, nothing fancy.

fix of a typo

---

src/winetricks
tests/winetricks-test

dotnet45 doesn't work yet, but it's progress.

Fix dotnet40

---

src/winetricks

OSX doesn't have anything for this, and if anyone on Solaris wants to,
they can send a PR.

winetricks: introduce $W_TASKSET, for Linux/FreeBSD support

---

Makefile
debian/copyright
src/winetricks

Just tell me if I should make separate PRs and/or split up the commits more.
Greets!
jre

documentation, copyright and appdata

---

src/winetricks

http://dict.concised.moe.edu.tw/cgi-bin/jbdic/gsweb.cgi?o=djbdic&searchid=Z00000041357

zh_TW typo

---

src/winetricks

vc2010express: switch from archive.org to a working URL

---

src/winetricks

vulkan updates

---

src/winetricks

Automatically workaround WineHQ bug #39403

Fix steam verb

---

src/winetricks

sound: restore verbs (from 50197be)

---

src/winetricks

dxvk54: update verb - set minimum Wine version of 3.6
See: [Github doitsujin/dxvk: Common issues](https://github.com/doitsujin/dxvk/wiki/Common-issues).

dxvk62: new verb

---

src/winetricks

foobar2000 v1.4 final is now available.

foobar2000: update to v1.4

---

src/winetricks

mdac27: update download URL

---

src/winetricks

kindle: update download URL

---

src/winetricks

flash: update to 29.0.0.171

---

src/winetricks

dxvk helper/verbs: add support for d3d10

---

src/winetricks.bash-completion

Fixes: https://github.com/Winetricks/winetricks/issues/1108

winetricks.bash-completion: remove shebang from header

---

src/winetricks

RE: https://forum.winehq.org/viewtopic.php?f=8&t=31306

improve error handling, for winetricks temporary directory setup

---

src/winetricks

directx9: install devenum, quartz, msdmo and qcap

---

src/winetricks

This helps to work around [Bug 34622](https://bugs.winehq.org/show_bug.cgi?id=34622) more easily.

qasf: new verb

---

src/winetricks

Fixes https://bugs.winehq.org/show_bug.cgi?id=44005.

ie8: Override ieproxy to native and copy it to system32.

---

src/winetricks

See: https://github.com/doitsujin/dxvk/issues/773

dxvk80: update sha256sum

---

src/winetricks

msxml3: force silent install

---

src/winetricks

This PR adds 64bit support to quartz and qasf and also adds some missing dll registrations.

64bit fixes

---

src/winetricks

Updated shasum256 and version for adobeair

Updated shasum256 and version for adobeair

---

src/winetricks

Add new settings `mimeassoc=on|off` to configure newly-available MIME
associations checkbox in winecfg.

settings: add 'MIME-type file associations' boolean

---

src/winetricks

See https://github.com/iXit/wine-nine-standalone
This adds the current release https://github.com/iXit/wine-nine-standalone/releases/tag/v0.2

galliumnine02: new verb

---

src/winetricks

@austin987 
I've done a:
git diff HEAD~1 HEAD
commit check this time! :-)

new verb: dxvk102

---

src/winetricks

Fixes: https://github.com/Winetricks/winetricks/issues/1200

dxvk: update RELEASE download URL

---

src/winetricks

@austin987 
I've updated all the dxvk verbs as discussed on IRC. I've also switched over to the Github API (release.json) for pulling the latest release version.

dxvk verb update

---

files/verbs/all.txt
files/verbs/dlls.txt
files/verbs/download.txt
src/winetricks

This is needed for Secret of Monkey Island 2 SE, see:
https://forum.winehq.org/viewtopic.php?f=8&t=31763#p120227

new verb: d3dcompiler_42

---

src/winetricks

https://www.libsdl.org/release/changes-1.2.html

sdl: update to 1.2.15

---

debian/control
src/winetricks

I just wanted to remove the deprecated ppa ubuntu-wine, but then started updating debian/. While doing that I tried to minimize the diff to Debian's version.
Please have a look at the single commit messages for some notes.

Update debian packaging and ubuntu instructions

---

src/winetricks

Use Internet Archive link for WMP9

---

src/winetricks

* new verb: dxvk130 
* dxvk verb: use Github API to get latest release

dxvk updates

---

src/winetricks

w_unset_winver: bump winver to win7

---

src/winetricks

Removed w_unset_winver and defined default for w_set_winver
Signed-off-by: Jacob Hrbek <werifgx@gmail.com>

w_set_winver: Attempt to improve version uncheck

---

src/winetricks

This just adds the missing v0.4 and the just released v0.5
Thanks!

add latest galliumnine releases

---

src/winetricks

Fixes: #1369
Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>

vcrun2015/7: Added dll required for battle.net

---

README.md

Highlight keywords in tests
Signed-of-by: Thomas McWork <thomas.mc.work@gmail.com>

README: Highlight keywords in tests

---

src/winetricks

* Wine 4.20 imports Vulkan version 1.1.126

dxvk130-dxvk144,dxvk verbs: update recommended Wine version

---

src/winetricks

@alesliehughes
As I mentioned in #1448, it would be nice to have wine bugs for these to reference in the workaround

mdac updates

---

src/winetricks

Got links from here https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Add vcrun2019 verb

---

src/winetricks

Create Source Han Sans fonts verbs and update fakechinese

---

src/winetricks

@austin987 
You might want to merge: https://github.com/Winetricks/winetricks/pull/1482 ; to retain attribution... I'll remove that part of the update from the **dxvk_master** verb.
Robert

Update helper_dxvk_d9vk: add d3d10core parameter

---

src/winetricks

qdvd: register dll

---

src/winetricks

msxml6: use archive.org

---

src/winetricks

The present installation can not create the correct desktop profile, it shoud be fixed by this pull request.

Update QQ to 8.9.6 and fix the wrong desktop profile installation.

---

README.md

Fix installation script's systemd service

---

src/winetricks

Microsoft seems to be removing more stuff again...

wmp10: use archive.org

---

.shellcheckrc
misc/bisect-wine-winetricks.sh
misc/convert_sha1_sha256.sh
misc/travis-install-bashate-deb.sh
src/linkcheck.sh
src/release.sh
src/uniquefiles.sh
src/winetricks
tests/shell-checks
tests/winetricks-dotnet-grid-test
tests/winetricks-test

Inspired by @ferion11 (see #1595).

misc: enforce braces around variables

---

src/winetricks

I used --force to test. (Didn't actually check that it installs correctly, because it shouldn't)

dotnet30sp1: use archive.org

---

src/winetricks

adds verbs for the latest (`lavfilters`) and last XP-supported version (`lavfilters702`) of [LAVFilters](https://github.com/Nevcairiel/LAVFilters)

lavfilters: new verbs

---

src/winetricks

art2kmin: downgrade back to older version and split newer version off

---

src/winetricks

I seem to have missed this when I updated the URL, my bad.

winxpsp3: fix setup filename.

---

src/winetricks

mfc70: new verb

---

src/winetricks

This takes care of the last request in #1517.
It should also help to run apps that need SAPI in Win 7 mode.

sapi: new verb

---

src/winetricks

dotnet11: set fusion to native after installing

---

src/winetricks

For #1672
@rmi1974, any chance you could test? I don't have the game myself to test.

d3dcompiler_46: new verb

---

src/winetricks

This PR should make most, if not all, WineD3D registry verbs compliant again. I tried to add justifications where needed, but feel free to ask more info if needed.

WineD3D registry verbs overhaul

---

src/winetricks

vcrun2019: update hashes

---

src/winetricks

busybox: update to FRP-3902-g61e53aa93

---

src/winetricks

- some texts translated
- Fixes Winetricks/winetricks#1633

Improved German translations

---

src/winetricks

Hi Austin,
vcrun2019 hashes changed, again. This PR updates the hashes accordingly.
Greets
jre

vcrun2019: update shasums

---

src/winetricks

galliumnine08: new verb

---

src/winetricks

No idea why MS decided to change these old installers, but here we are...

Update vcrun2010 hashes

---

src/winetricks

For now this only contains a commit to update the hashes, but I can change it to include a fix for #1770 once we figure out a solution for it.

vcrun2019 updates

---

src/winetricks

Add vkd3d verb to install latest vkd3d-proton release

New verb: vkd3d

---

src/winetricks

Bump cnc_ddraw to the latest version

cnc_ddraw: update to 4.4.4.0

---

src/winetricks

dotnet462: use archive.org for download

---

src/winetricks

dotnet472: update url & sha256 checksum

---

src/winetricks

Here `down` does not mean `download`.

fix a wrong Chinese translation

---

src/winetricks

Translation to Portuguese

---

src/winetricks

@austin987 I've had to refactor the dxvk version numbers again (!!)

update dxvk verbs

---

src/winetricks

remove_mono internal: no warning when wine-mono is not installed
dotnet* vc2010express: update verbs to call remove_mono internal
Closes: #1920

remove_mono: support 'internal' argument

---

src/winetricks

winecmd: new verb

---

src/winetricks

Add support for 32-bit/64-bit Windows version(s) of WinRAR
Closes: #1694

new verb: winrar

---

files/verbs/all.txt
files/verbs/apps.txt
files/verbs/download.txt
src/winetricks

Hi,
since I had problems with the squashing last time, here is a new attempt.I hope this time it is ok.
Update Uplay to Ubisoft Connect.

UPlay replaced by Ubisoft Connect

---

src/winetricks

See issue... https://github.com/Winetricks/winetricks/issues/1957

Update vcrun2015 to install VC++ 2015 Update 3 ?

---

src/winetricks

While at it, I also updated the year numbers of the most recent versions.

New verb: dxvk2010

---

src/winetricks

see https://github.com/Winetricks/winetricks/issues/2047#issue-1628313156

Rename faudio latest to 20.07

---

src/winetricks

Hello there, this is the Bulgarian translation for Winetricks.
This PR is ready for review although I need help with one specific thing related to WinRAR. Currently I'm using the default English version of it because I have no idea how to see the checksums (?) for the Bulgarian version. Could someone give me a hand for this (write the checksums here)? The lines are 17055 and 17057. Thanks in advance!
Also, I would like to ask if this is everything I need to do, for example do I need to edit other files?
Regards,
Georgi

Adding Bulgarian Translation

---

files/verbs/all.txt
files/verbs/settings.txt
src/winetricks

Add win11 support

---

src/winetricks

Update dotnet6 and dotnetdesktop6 to 6.0.16

---

src/winetricks

Happy vacation day (if you have it!)

Update dotnet6 and dotnetdesktop6 to 6.0.19

---

src/winetricks

winetricks_misc_exe: add an option in the GUI to run an arbitrary executable

---

src/winetricks

vlgothic: update url mirror

---

src/winetricks

uiribbon: new verb

---

src/winetricks

This one took quite a while to make...
Does Winetricks have anything else available for translation? I'm asking this because only recently I found out about the title strings. :smiley: 
EDIT: I have no idea what is wrong about line 3941.
Best regards,
Georgi

Updated Bulgarian Translation

---

src/winetricks

xaudio29: new verb

---

src/winetricks

Closes https://github.com/Winetricks/winetricks/issues/2148

msxml3: Update to newer version; add 64-bit support

---

src/winetricks

`Diablo 2 LoD Glide to OpenGL Wrapper`
This glide wrapper really improves Diablo2: Lord of Destruction

d2gl: new verb

---

src/winetricks

closes https://github.com/Winetricks/winetricks/issues/2186

dotnet8|dotnetdesktop8: new verbs

---

files/verbs/apps.txt
src/winetricks

This pull request adds [process explorer](https://learn.microsoft.com/de-de/sysinternals/downloads/process-explorer) to winetricks.

procexp: new verb

---

src/winetricks

See https://bugs.winehq.org/show_bug.cgi?id=20054

micross: new verb

---

src/winetricks

vcrun2022: Update hashes

---

src/winetricks

opensymbol: download from archive.debian.org

---

src/winetricks

Update the following dotnet versions
- 8.0.2 -> 8.0.8
- 7.0.14 -> 7.0.20
- 6.0.19 -> 6.0.33
Closes #2263

Update the dotnet version

---

src/winetricks

Fixing missing space in dotnetdesktop8

---

src/winetricks

Add D3D8 support to DXVK

---

src/winetricks

This requires #2244 to handle the d3d8 library

dxvk: New verbs

---

src/winetricks

Resolves https://github.com/Winetricks/winetricks/issues/2309

vcrun2015/17/19/22: manually install msvcp140.dll

---

src/winetricks

This updates verb for PhysX_9.23.1019_SystemSoftware.exe

PhysX: Update version

---

files/verbs/all.txt
files/verbs/dlls.txt
files/verbs/download.txt
src/winetricks

Add missing parts for dxvk2053 too

dxvk2060/dxvk2061/dxvk2062: New verbs

---

src/winetricks

Rename w_try_regsvr to w_try_regsvr32 to align with w_try_regsvr64.
Also it fixes issue #2347

Rename w_try_regsvr() to w_try_regsvr32()

---

src/winetricks

fix for https://github.com/Winetricks/winetricks/issues/2347

ie8: removed dll that cannot be registered

---

src/winetricks

Update Simplified Chinese translation

Update Simplified Chinese translation

---

src/winetricks

Hello,
In the Polish translation there was a small typo. This change is very minor - just one letter.
Thanks!

misc: Fixed a typo
